PUT http://localhost:9191/borrowed/4
Accept: application/json
Content-Type: application/json

{
  "id_book" : 3,
  "quantity_back" : 5
}
###
##
GET http://localhost:9191/borrowed
Accept: application/json


###
GET http://localhost:9191/book
Accept: application/json

###
###
PUT http://localhost:9191/book/4
Content-Type: application/json



###
POST http://localhost:9191/borrowed
Accept: application/json
Content-Type: application/json

{
  "id_borrower" : 1,
  "id_book" : 1,
  "quantity_borrowed" : 20
}

###
POST http://localhost:9191/book/
Accept: application/json
Content-Type: application/json

{
  "title" : "tema 5",
  "quantity" : 100
}


